### ISSUE TITLE
Use data_noisy for estimation, instead of data

### ISSUE THREAD

**Issue by kakila** [smrfeld/Total-Variation-Regularization-Derivative-Python#1]
The algorithm is receiving the pure data, data_noisy is used instead the result is not that good.

https://github.com/smrfeld/Total-Variation-Regularization-Derivative-Python/blob/ffdf043bdf11356672c9d52e2824e68c3114af73/python/example_abs.py#L40

**Comment by smrfeld** [comment]
Indeed this was a bug, thanks
I fixed it and remade the figure, honestly it looks qualitatively very similar to me as before, also very similar to the one from Mathematica

**Comment by kakila** [comment]
you are right, it was my mistake, forgot to add the initial value back to the reconstructed signal.
